name: npt
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch==2.0
  - torchvision
  - pip
  - pip:
    - wandb
    - scikit-learn
    - pandas
    - pycodestyle
    - dotmap
    - line-profiler
    - tqdm
    - pytorch-lightning
    - patool
    - wget
    - scikit-optimize
    - xgboost
    - catboost
    - transformers
    - numba
    - ogb
    - memory-profiler
    - seaborn
    - tensorboardX
    - tensorboard
    - seaborn
    - fairseq
    - dotmap
    # - pytorch-tabnet # downgrades torch below 2.0.0
    # - tabnet
    # - lightgbm
    - jupyterlab
    - notebook
    - matplotlib
    - qhoptim
    # - torchvision
    - gpytorch